[config.wallpaper]
command = "/home/jakulej/.config/hypr/scripts/changeWallpaper.sh"
set = true

[templates.hyprland]
input_path = '~/files/dotfiles/matugen/templates/hyprland-colors.conf'
output_path = '~/files/dotfiles/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/files/dotfiles/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/files/dotfiles/kitty/colors.conf'

[templates.rofi]
input_path = './templates/rofi-colors.conf'
output_path = '~/files/dotfiles/rofi/colors.rasi'

[templates.hyprpaper]
input_path = './templates/hyprpaper-wallpaper.conf'
output_path = '~/files/dotfiles/hypr/hyprpaper.conf'
