[config.wallpaper]
command = "hyprpaper"

[templates.hyprland]
input_path = '~/files/dotfiles/matugen/templates/hyprland-colors.conf'
output_path = '~/files/dotfiles/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/files/dotfiles/waybar/colors.css'
#post_hook = 'pkill -SIGUSR2 waybar'
